app = "tic-uzd3zg" # Mude para o nome do seu app na Fly.io
primary_region = "iad"     # gru = São Paulo (mude para iad se o seu Mongo estiver na Virgínia)

[build]
  dockerfile = "Dockerfile"

[env]
  CORS_ALLOWED_ORIGINS = "https://tic-front-5jjg8t3dz-number11.vercel.app/"

[[services]]
  internal_port = 33177    
  protocol = "tcp"        

  [[services.ports]]
    handlers = []         
    port = 33177         
