app = "tic-uzd3zg" # Mude para o nome do seu app na Fly.io
primary_region = "iad"   

[build]
  dockerfile = "Dockerfile"

[env]
  CORS_ALLOWED_ORIGINS = "https://jogodavelha.site,https://www.jogodavelha.site"

[[services]]
  internal_port = 33177    
  protocol = "tcp"        

  [[services.ports]]
    handlers = []         
    port = 33177         
